package com.example.telegramapi.enums;

public enum States {
    CONVERSATION_STARTED,
    MENU,
    SETTINGS,
    CHANGE_LANGUAGE,
    FIRST_LANGUAGE_CHANGE,
    SUCCESSFULLY_CHANGED_SETTINGS,
    CHANGE_NATIVE,
    ABOUT,
    TEST_TAB,
    WAITING_FOR_LIST,
    WAIT_FOR_LANG_PAIR,
    GENERATED_RANDOM_LIST,
    RETURNED_USER_LIST,
    PREPARES_LIST,
    TEST_STARTED,
    TEST_FINISHED,
    PREPARES_TEST,
    ASSIGNMENTS,
    WAITING_FOR_AMOUNT,
    WAITING_FOR_LEVEL,
    WAITING_FOR_LANG_BEFORE_RANDOM,
    FURTHER_QUERY,
    CHOOSE_NATIVE_BEFORE,
    HELP
}
